---
resources:
- name: isv-docs-master
  type: git
  source:
    uri: git@github.com:cf-platform-eng/isv-docs.git
    private_key: ((isv-docs-deploy-key-ci))
    branch: master

- name: isv-docs-gh-pages
  type: git
  source:
    uri: git@github.com:cf-platform-eng/isv-docs.git
    private_key: ((isv-docs-deploy-key-ci))
    branch: gh-pages


jobs:
  - name: deploy-isv-docs
    build_log_retention:
        builds: 10
    plan:
    - in_parallel:
      - get: isv-docs-gh-pages
      - get: isv-docs-master
        trigger: true

    - do:
      - task: build-mkdocs
        input_mapping:
          mkdocs-in: isv-docs-master
        config:
          inputs:
            - name: mkdocs-in
          outputs:
            - name: mkdocs-site-out
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: dherbrich/mkdocs-material-awesome-pages
              tag: 0.1.0
          run:
            path: /bin/sh
            args:
              - -exc
              - |
                 mkdocs build -f "${PWD}/mkdocs-in/mkdocs.yml" -d "${PWD}/mkdocs-site-out"

      - task: deploy-isv-tech-hub-ghpages
        input_mapping:
          mkdocs-site-in: mkdocs-site-out
        config:
          inputs:
            - name: mkdocs-site-in
            - name: isv-docs-gh-pages
          outputs:
            - name: isv-docs-gh-pages
          platform: linux
          image_resource:
            type: registry-image
            source: 
              repository: alpine/git
              tag: latest
          run:
            path: /bin/sh
            args:
            - -exc
            - |
                function check_in() {
                  git add .
                  git config --global user.email cf-platform-eng+ci@pivotal.io
                  git config --global user.name ISVTechHubCI
                  git commit -am"$1" || true ;
                }
                
                rm -rf ./isv-docs-gh-pages/*
                cp -a ./mkdocs-site-in/. ./isv-docs-gh-pages

                cd ./isv-docs-gh-pages
                git status
                check_in ":whale: Update ISV Tech Hub Docs"
                git status
              
        on_success:
          put: isv-docs-gh-pages
          params: {rebase: true, force: true, repository: isv-docs-gh-pages }
